/**
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.module;

import java.util.Random;

import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.oauth.OAuth;
import org.mule.api.annotations.oauth.OAuthAccessToken;
import org.mule.api.annotations.oauth.OAuthAccessTokenSecret;
import org.mule.api.annotations.oauth.OAuthAuthorizationParameter;
import org.mule.api.annotations.oauth.OAuthConsumerKey;
import org.mule.api.annotations.oauth.OAuthConsumerSecret;
import org.mule.api.annotations.oauth.OAuthProtected;
import org.mule.api.annotations.param.Default;
import org.mule.api.annotations.param.Optional;
import org.mule.api.annotations.rest.RestCall;
import org.mule.api.annotations.rest.RestExceptionOn;
import org.mule.api.annotations.rest.RestQueryParam;
import org.mule.api.annotations.rest.RestUriParam;

/**
 * Cloud Connector
 *
 * @author MuleSoft, Inc.
 */
@Connector(name="bodymedia", schemaVersion="1.0-SNAPSHOT", friendlyName="Body Media", minMuleVersion="3.4.0", description="Body Media Connector")
@OAuth(requestTokenUrl = "https://api.bodymedia.com/oauth/request_token?api_key=333rrb2uf254wbpzckq8u64ugzcayteh",
accessTokenUrl = "https://api.bodymedia.com/oauth/access_token", 
authorizationUrl = "https://api.bodymedia.com/oauth/authorize",
verifierRegex = "oauth_token=([^&]+)",
authorizationParameters = {@OAuthAuthorizationParameter(name="api_key", optional=false, type=String.class, description="The Consumer Key (API Key) provided to you when you signed up. This value is required by Mashery and will be the same value as the oauth_consumer_key above. This must be included as a seperate HTTP GET or HTTP POST parameter and is not part of the Oauth Authentication header.")})
public abstract class BodyMediaConnector
{
    /**
     * Consumer Key
     */
    @OAuthConsumerKey
    @Configurable
    private String consumerKey;

    /**
     * Consumer Secret
     */
    @OAuthConsumerSecret
    @Configurable
    private String consumerSecret;
    
    /**
     * Access token
     */
    @OAuthAccessToken
    private String accessToken;
 
    /**
     * Access token secret
     */
    @OAuthAccessTokenSecret
    private String accessTokenSecret;

    /**
     * API Key
     */
    @Configurable
    @RestQueryParam("api_key")
    private String apiKey;
    
    public String getConsumerKey()
    {
        return consumerKey;
    }

    public void setConsumerKey(String consumerKey)
    {
        this.consumerKey = consumerKey;
    }

    public String getConsumerSecret()
    {
        return consumerSecret;
    }

    public void setConsumerSecret(String consumerSecret)
    {
        this.consumerSecret = consumerSecret;
    }

    public String getAccessToken()
    {
        return accessToken;
    }

    public void setAccessToken(String accessToken)
    {
        this.accessToken = accessToken;
    }

    public String getAccessTokenSecret()
    {
        return accessTokenSecret;
    }

    public void setAccessTokenSecret(String accessTokenSecret)
    {
        this.accessTokenSecret = accessTokenSecret;
    }

    public String getApiKey()
    {
        return apiKey;
    }

    public void setApiKey(String apiKey)
    {
        this.apiKey = apiKey;
    }
    
    /**
     * Returns the caloric burn total and average for a given day
     * 
     * {@sample.xml ../../../doc/BodyMedia-connector.xml.sample bodymedia:get-average-total-caloric-burn}
     * @param startDate The start day
     * @param endDate The end day
     * @return caloric total burn
     * @throws Exception In case of exeption
     */
    @OAuthProtected
    @Processor    
    @RestCall(uri = "http://api.bodymedia.com/v2/burn/{startDate}/{endDate}", contentType="application/xml", method = org.mule.api.annotations.rest.HttpMethod.GET, exceptions={@RestExceptionOn(expression="#[message.inboundProperties['http.status'] != 200]")})
    public abstract String getAverageTotalCaloricBurn(@RestUriParam("startDate") String startDate, @RestUriParam("endDate") @Optional @Default("") String endDate) throws Exception;
}
